name: sanctions-audit
region: fra1

services:
  # Backend API service (FastAPI + Playwright)
  - name: backend
    source_dir: /backend
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: professional-xs
    health_check:
      http_path: /health
      initial_delay_seconds: 40
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /api
        preserve_path_prefix: true
    envs:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DO_SPACES_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DO_SPACES_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: DO_SPACES_ENDPOINT
        scope: RUN_TIME
        value: "https://nyc3.digitaloceanspaces.com"
      - key: DO_SPACES_REGION
        scope: RUN_TIME
        value: "nyc3"
      - key: DO_BUCKET_NAME
        scope: RUN_TIME
        value: "sanctions-audit"
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET

  # Frontend service (Next.js)
  - name: frontend
    source_dir: /frontend
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_BACKEND_URL
        scope: RUN_AND_BUILD_TIME
        value: ${backend.PUBLIC_URL}/api
      - key: BACKEND_URL
        scope: RUN_TIME
        value: ${backend.PRIVATE_URL}
